backend:
  name: github
  repo: daotrungkienhp/content
  branch: main
  site_domain: daotrungkien.netlify.app

site_url: https://daotrungkienhp.github.io/content/

media_folder: "images/uploads"

collections:
  - name: "Rmd Pages"
    label: "Rmarkdown"
    format: "yaml-frontmatter"
    files:
      - label: "Index"
        name: "index"
        file: "index.Rmd"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "Markdown Pages"
    label: "markdown"
    files:
      - label: "readme"
        name: "readme"
        file: "README.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          
